services:
  - type: web
    name: arcodm-subscription
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_URL
        value: https://t.me/ar8codm
      - key: ADMIN_KEY
        sync: false
