services:
  - type: web
    name: arcodm-subscription
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://arcodm-subscription.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: arcodm-subscription-db
          property: connectionString
      - key: TELEGRAM_URL
        value: https://t.me/ar8codm
      - key: ADMIN_KEY
        sync: false

databases:
  - name: arcodm-subscription-db
    plan: free
    databaseName: arcodm_subscription
